import { Activity, LeaderboardEntry, Match, MatchPlayer, Profile, Team, Turf } from "./types";
import { getInitials } from "./utils";

const makePlayers = (matchId: string, names: string[]): MatchPlayer[] =>
  names.map((name, index) => ({
    id: `${matchId}-player-${index + 1}`,
    match_id: matchId,
    profile_id: `profile-${index + 1}`,
    full_name: name,
    initials: getInitials(name),
    status: index === 0 ? "in" : index === 1 ? "on_the_way" : "waiting",
    paid: true,
    checked_in: index === 0,
  }));

export const currentProfile: Profile = {
  id: "profile-1",
  full_name: "Brian Otieno",
  username: "briano10",
  email: "brian@example.com",
  city: "Nairobi",
  position: "Midfielder",
  skill_level: "Advanced",
  reliability_score: 92,
  matches: 18,
  wins: 11,
  goals: 9,
  assists: 6,
  rating: 4.8,
  verified: true,
};

export const matches: Match[] = [
  {
    id: "match-1",
    title: "Upper Hill Tuesday Pickup",
    type: "Pickup",
    format: "5-a-side",
    skill_level: "Intermediate",
    location: "Ligi Ndogo, Nairobi",
    city: "Nairobi",
    date: "2026-03-24",
    start_time: "18:30",
    end_time: "20:00",
    total_cost: 6000,
    max_players: 10,
    joined_players: 7,
    organiser_name: "Kevin Mwangi",
    organiser_id: "profile-2",
    status: "Open",
    is_paid: true,
    description: "Fast-paced after-work football with balanced teams and quick roll-on rotations if we fill early.",
    organiser_bio: "Kevin runs weekday pickup games across Nairobi and confirms slots only after payment clears.",
    players: makePlayers("match-1", ["Brian Otieno", "Kevin Mwangi", "Amani Yusuf", "David Kiptoo", "John Mugo", "Ian Ochieng", "Samir Ali"]),
  },
  {
    id: "match-2",
    title: "Mombasa Floodlit Challenge",
    type: "Competitive",
    format: "7-a-side",
    skill_level: "Advanced",
    location: "Nyali Sports Centre, Mombasa",
    city: "Mombasa",
    date: "2026-03-25",
    start_time: "19:00",
    end_time: "21:00",
    total_cost: 9800,
    max_players: 14,
    joined_players: 12,
    organiser_name: "Sarah Wambui",
    organiser_id: "profile-3",
    status: "Open",
    is_paid: true,
    description: "Competitive floodlit game for players who want a sharper tempo and organized subs.",
    organiser_bio: "Sarah captains Coast Ballers and organizes premium evening fixtures in Mombasa.",
    players: makePlayers("match-2", ["Sarah Wambui", "Allan Biko", "Fahad Omar", "Joan Chelangat", "Ian Ochieng", "Dennis Kimani", "Musa Abdallah", "Betty Achieng"]),
  },
  {
    id: "match-3",
    title: "Kisumu Sunrise Free Kickabout",
    type: "Pickup",
    format: "6-a-side",
    skill_level: "Any",
    location: "Jomo Kenyatta Grounds, Kisumu",
    city: "Kisumu",
    date: "2026-03-26",
    start_time: "07:00",
    end_time: "08:30",
    total_cost: 0,
    max_players: 12,
    joined_players: 6,
    organiser_name: "Brian Otieno",
    organiser_id: "profile-1",
    status: "Open",
    is_paid: false,
    description: "Casual sunrise kickabout before work. Bring boots, water, and a teammate if you have one.",
    organiser_bio: "Brian likes running low-friction community games that start on time.",
    players: makePlayers("match-3", ["Brian Otieno", "Tino Oduor", "Mike Aura", "Eva Moraa", "Clinton Ouma", "Mary Akinyi"]),
  },
];

export const teams: Team[] = [
  {
    id: "team-1",
    name: "Nairobi Strikers",
    city: "Nairobi",
    role: "Captain",
    initials: "NS",
    skill_level: "Advanced",
    matches: 24,
    wins: 16,
    win_rate: 67,
    recruiting: true,
  },
  {
    id: "team-2",
    name: "Coast Ballers",
    city: "Mombasa",
    role: "Member",
    initials: "CB",
    skill_level: "Intermediate",
    matches: 19,
    wins: 10,
    win_rate: 53,
    recruiting: false,
  },
  {
    id: "team-3",
    name: "Kisumu Rapids",
    city: "Kisumu",
    role: "Recruiting",
    initials: "KR",
    skill_level: "Intermediate",
    matches: 14,
    wins: 8,
    win_rate: 57,
    recruiting: true,
  },
];

export const turfs: Turf[] = [
  {
    id: "turf-1",
    name: "Ligi Ndogo Arena",
    location: "Ngong Road, Nairobi",
    city: "Nairobi",
    rating: 4.8,
    price_per_hour: 3500,
    amenities: ["Floodlights", "Changing Rooms", "Parking"],
    available_now: true,
    floodlit: true,
    indoor: false,
  },
  {
    id: "turf-2",
    name: "Nyali Indoor Dome",
    location: "Nyali, Mombasa",
    city: "Mombasa",
    rating: 4.6,
    price_per_hour: 4200,
    amenities: ["Indoor", "Parking", "Showers"],
    available_now: false,
    floodlit: false,
    indoor: true,
  },
  {
    id: "turf-3",
    name: "Lake Basin Floodlit",
    location: "Milimani, Kisumu",
    city: "Kisumu",
    rating: 4.5,
    price_per_hour: 3000,
    amenities: ["Floodlights", "Parking"],
    available_now: true,
    floodlit: true,
    indoor: false,
  },
];

export const activities: Activity[] = [
  { id: "act-1", match_name: "Upper Hill Tuesday Pickup", date: "2026-03-20", goals: 1, assists: 2, result: "WIN" },
  { id: "act-2", match_name: "Westlands Friday Lights", date: "2026-03-16", goals: 0, assists: 1, result: "DRAW" },
  { id: "act-3", match_name: "CBD Lunchtime 5v5", date: "2026-03-11", goals: 2, assists: 0, result: "LOSS" },
];

export const leaderboard: LeaderboardEntry[] = [
  { id: "lb-1", rank: 1, name: "Dennis Kimani", initials: "DK", position: "Forward", location: "Nairobi", value: 18 },
  { id: "lb-2", rank: 2, name: "Sarah Wambui", initials: "SW", position: "Midfielder", location: "Mombasa", value: 16 },
  { id: "lb-3", rank: 3, name: "Amani Yusuf", initials: "AY", position: "Defender", location: "Kisumu", value: 14 },
  { id: "lb-4", rank: 4, name: "Joan Chelangat", initials: "JC", position: "Forward", location: "Nakuru", value: 12 },
  { id: "lb-5", rank: 5, name: "Brian Otieno", initials: "BO", position: "Midfielder", location: "Nairobi", value: 9, isCurrentUser: true },
];
